export type AllergyIntensity = "Baja" | "Media" | "Alta";
export type AllergyCategory =
  | "Crustáceos"
  | "Mariscos"
  | "Pescados"
  | "Frutas"
  | "Vegetales"
  | "Frutos secos"
  | "Árboles"
  | "Hongos"
  | "Animales"
  | "Especias"
  | "Semillas"
  | "Proteinas";

export interface AlergiaType {
  name: string;
  isAlergic: boolean;
  intensity: AllergyIntensity;
  category: AllergyCategory;
  KUA_Litro?: number;
}
export const arrayAlergias: AlergiaType[] = [
  {
    name: "Frutos secos",
    isAlergic: true,
    intensity: "Alta",
    category: "Frutos secos",
    KUA_Litro: 20.0,
  },
  {
    name: "Proteina LTP",
    isAlergic: true,
    intensity: "Alta",
    category: "Proteinas",
    KUA_Litro: 20.0,
  },
  {
    name: "Mariscos",
    isAlergic: true,
    intensity: "Alta",
    category: "Mariscos",
    KUA_Litro: 20.0,
  },
  {
    name: "Crustáceos general",
    isAlergic: true,
    intensity: "Alta",
    category: "Crustáceos",
    KUA_Litro: 20.0,
  },
  {
    name: "Gamba",
    isAlergic: true,
    intensity: "Alta",
    category: "Crustáceos",
    KUA_Litro: 1.36,
  },
  {
    name: "Almeja",
    isAlergic: false,
    intensity: "Baja",
    category: "Mariscos",
    KUA_Litro: 0.04,
  },
  {
    name: "Mejillón",
    isAlergic: false,
    intensity: "Baja",
    category: "Mariscos",
    KUA_Litro: 0.01,
  },
  {
    name: "Atún",
    isAlergic: false,
    intensity: "Baja",
    category: "Pescados",
    KUA_Litro: 0.11,
  },
  {
    name: "Calamar",
    isAlergic: false,
    intensity: "Baja",
    category: "Mariscos",
    KUA_Litro: 0.02,
  },
  {
    name: "Bacalao",
    isAlergic: false,
    intensity: "Baja",
    category: "Pescados",
    KUA_Litro: 0.01,
  },
  {
    name: "Merluza",
    isAlergic: false,
    intensity: "Baja",
    category: "Pescados",
    KUA_Litro: 0.02,
  },
  {
    name: "Gallo",
    isAlergic: false,
    intensity: "Baja",
    category: "Pescados",
    KUA_Litro: 0.03,
  },
  {
    name: "Salmón",
    isAlergic: false,
    intensity: "Baja",
    category: "Pescados",
    KUA_Litro: 0.01,
  },
  {
    name: "Tomate",
    isAlergic: true,
    intensity: "Media",
    category: "Vegetales",
    KUA_Litro: 0.1,
  },
  {
    name: "Melocotón",
    isAlergic: true,
    intensity: "Alta",
    category: "Frutas",
    KUA_Litro: 13.2,
  },
  {
    name: "Melocotón LTP",
    isAlergic: true,
    intensity: "Alta",
    category: "Frutas",
    KUA_Litro: 6.7,
  },
  {
    name: "Calabaza",
    isAlergic: true,
    intensity: "Alta",
    category: "Vegetales",
    KUA_Litro: 2.94,
  },
  {
    name: "Pipa Calabaza",
    isAlergic: true,
    intensity: "Alta",
    category: "Frutos secos",
    KUA_Litro: 2.94,
  },
  {
    name: "Cacahuete",
    isAlergic: true,
    intensity: "Alta",
    category: "Frutos secos",
    KUA_Litro: 4.96,
  },
  {
    name: "Avellana",
    isAlergic: true,
    intensity: "Alta",
    category: "Frutos secos",
    KUA_Litro: 1.83,
  },
  {
    name: "Avellana LTP",
    isAlergic: true,
    intensity: "Alta",
    category: "Frutos secos",
    KUA_Litro: 2.45,
  },
  {
    name: "Nuez",
    isAlergic: true,
    intensity: "Alta",
    category: "Frutos secos",
    KUA_Litro: 3.55,
  },

  {
    name: "Almendra",
    isAlergic: true,
    intensity: "Media",
    category: "Frutos secos",
    KUA_Litro: 2.64,
  },
  {
    name: "Piñón",
    isAlergic: false,
    intensity: "Baja",
    category: "Frutos secos",
    KUA_Litro: 0.24,
  },
  {
    name: "Anacardo",
    isAlergic: false,
    intensity: "Baja",
    category: "Frutos secos",
    KUA_Litro: 0.01,
  },
  {
    name: "Pistacho",
    isAlergic: false,
    intensity: "Baja",
    category: "Frutos secos",
    KUA_Litro: 0.05,
  },
  {
    name: "Cipres",
    isAlergic: true,
    intensity: "Alta",
    category: "Árboles",
    KUA_Litro: 22.7,
  },
  {
    name: "Calabacin",
    isAlergic: true,
    intensity: "Alta",
    category: "Vegetales",
    KUA_Litro: 7.0,
  },
  {
    name: "Pimiento rojo",
    isAlergic: true,
    intensity: "Alta",
    category: "Vegetales",
    KUA_Litro: 5.0,
  },
  {
    name: "Fresa",
    isAlergic: true,
    intensity: "Alta",
    category: "Frutas",
    KUA_Litro: 5.0,
  },
  {
    name: "Aguacate",
    isAlergic: true,
    intensity: "Alta",
    category: "Vegetales",
    KUA_Litro: 5.0,
  },
  {
    name: "Berenjena",
    isAlergic: true,
    intensity: "Alta",
    category: "Vegetales",
    KUA_Litro: 5.0,
  },
  {
    name: "Piña",
    isAlergic: true,
    intensity: "Alta",
    category: "Vegetales",
    KUA_Litro: 5.0,
  },
  {
    name: "Melón",
    isAlergic: true,
    intensity: "Alta",
    category: "Vegetales",
    KUA_Litro: 5.0,
  },
  {
    name: "Paraguaya",
    isAlergic: true,
    intensity: "Alta",
    category: "Vegetales",
    KUA_Litro: 14.0,
  },
  {
    name: "Pepino",
    isAlergic: true,
    intensity: "Alta",
    category: "Vegetales",
    KUA_Litro: 5.0,
  },
  {
    name: "Pimiento verde",
    isAlergic: true,
    intensity: "Alta",
    category: "Vegetales",
    KUA_Litro: 5.0,
  },
  {
    name: "Berenjena",
    isAlergic: false,
    intensity: "Baja",
    category: "Vegetales",
    KUA_Litro: 0.12,
  },
  {
    name: "Calabaza",
    isAlergic: true,
    intensity: "Alta",
    category: "Vegetales",
    KUA_Litro: 4.0,
  },
  {
    name: "Hierba timonía",
    isAlergic: true,
    intensity: "Alta",
    category: "Árboles",
    KUA_Litro: 8.24,
  },
  {
    name: "Plátano de sombra",
    isAlergic: true,
    intensity: "Alta",
    category: "Árboles",
    KUA_Litro: 9.09,
  },
  {
    name: "Arizónica",
    isAlergic: true,
    intensity: "Alta",
    category: "Árboles",
    KUA_Litro: 16.2,
  },
  {
    name: "Nuez de nogal",
    isAlergic: true,
    intensity: "Alta",
    category: "Árboles",
    KUA_Litro: 7.2,
  },
  {
    name: "Alternaria alternata",
    isAlergic: true,
    intensity: "Alta",
    category: "Hongos",
    KUA_Litro: 10.2,
  },
  {
    name: "Trufa",
    isAlergic: true,
    intensity: "Alta",
    category: "Hongos",
    KUA_Litro: 0.0,
  },
  {
    name: "Perro",
    isAlergic: true,
    intensity: "Media",
    category: "Animales",
    KUA_Litro: 3.69,
  },
  {
    name: "Gato",
    isAlergic: true,
    intensity: "Alta",
    category: "Animales",
    KUA_Litro: 16.9,
  },
  {
    name: "Sandia",
    isAlergic: true,
    intensity: "Alta",
    category: "Vegetales",
    KUA_Litro: 5.0,
  },
  {
    name: "Melon",
    isAlergic: false,
    intensity: "Baja",
    category: "Frutas",
    KUA_Litro: 0.12,
  },
  {
    name: "Berenjena",
    isAlergic: false,
    intensity: "Baja",
    category: "Vegetales",
    KUA_Litro: 0.12,
  },
  {
    name: "Sandia",
    isAlergic: false,
    intensity: "Baja",
    category: "Frutas",
    KUA_Litro: 0.04,
  },
  {
    name: "Ciruela",
    isAlergic: true,
    intensity: "Alta",
    category: "Frutas",
    KUA_Litro: 5.55,
  },
  {
    name: "Pepino",
    isAlergic: true,
    intensity: "Media",
    category: "Vegetales",
    KUA_Litro: 1.59,
  },
  {
    name: "Pimienta verde",
    isAlergic: false,
    intensity: "Baja",
    category: "Especias",
    KUA_Litro: 0.0,
  },
  {
    name: "Fresas",
    isAlergic: true,
    intensity: "Media",
    category: "Frutas",
    KUA_Litro: 1.95,
  },
  {
    name: "Mango",
    isAlergic: false,
    intensity: "Baja",
    category: "Frutas",
    KUA_Litro: 0.03,
  },
  {
    name: "Castaña",
    isAlergic: false,
    intensity: "Baja",
    category: "Frutos secos",
    KUA_Litro: 0.13,
  },
  {
    name: "Piña",
    isAlergic: false,
    intensity: "Baja",
    category: "Frutas",
    KUA_Litro: 0.13,
  },
  {
    name: "Uva",
    isAlergic: false,
    intensity: "Baja",
    category: "Frutas",
    KUA_Litro: 0.48,
  },
  {
    name: "Kiwi",
    isAlergic: false,
    intensity: "Baja",
    category: "Frutas",
    KUA_Litro: 0.03,
  },
  {
    name: "Semilla de girasol",
    isAlergic: false,
    intensity: "Baja",
    category: "Semillas",
    KUA_Litro: 0.12,
  },
];
